#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("P4U.Droid.Resource", IsApplication=true)]

namespace P4U.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int ic_bar = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int ic_bus_station = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int ic_cafe = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int ic_cinema = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int ic_food = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int ic_gas_station = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int ic_location = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int ic_parking = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int ic_shopping_mall = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int ic_subway = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int ic_taxi_stand = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int ic_train = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int Icon = 2130837516;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060008
			public const int editTextSearch = 2131099656;
			
			// aapt resource value: 0x7f060007
			public const int gridViewHome = 2131099655;
			
			// aapt resource value: 0x7f060001
			public const int grid_text = 2131099649;
			
			// aapt resource value: 0x7f060000
			public const int imageViewHomeIcon = 2131099648;
			
			// aapt resource value: 0x7f060002
			public const int imageViewPictureResult = 2131099650;
			
			// aapt resource value: 0x7f06000a
			public const int listViewResult = 2131099658;
			
			// aapt resource value: 0x7f060009
			public const int search = 2131099657;
			
			// aapt resource value: 0x7f060006
			public const int textViewDetailsName = 2131099654;
			
			// aapt resource value: 0x7f060003
			public const int textViewNameResult = 2131099651;
			
			// aapt resource value: 0x7f060005
			public const int textViewPaysEtVilleEtCPResult = 2131099653;
			
			// aapt resource value: 0x7f060004
			public const int textViewRueResult = 2131099652;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int CustomGridViewHome = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int CustomListViewResult = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int DetailsSearch = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Main = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int ResultSearch = 2130903044;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040000
			public const int app_name = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f050000
			public const int Theme_Splash = 2131034112;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
